oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_pipeline_type: RGB
      i_ip: "192.168.123.20"
      i_enable_ir: false
      i_set_xlink_chunk_size: true
      i_xlink_chunk_size: 0
    rgb:
      i_resolution: "1080p"
      i_fps: 30.0
      i_publish_topic: true
    left:
      i_publish_topic: false
      i_resolution: "400p"
    right:
      i_publish_topic: false
      i_resolution: "400p"
    stereo:
      i_publish_topic: false
      i_align_depth: false
    nn:
      i_publish_topic: false
